### ISSUE TITLE
0.4.10-rc

### ISSUE THREAD

**Issue by masayuki0812** [masayuki0812/c3#1019]
`v0.4.10-rc1` has been released.
https://github.com/masayuki0812/c3/releases/tag/0.4.10-rc1

`v0.4.10` will be released after we confirm it works as we expect and has no regression bug. It would be appreciated if you test this version and let us know the issues that should be fixed. Thanks.

**Comment by aendrew** [comment]
Yay! :+1: :shipit:

**Comment by ergo** [comment]
Is it possible that the memory leak is now fixed?

**Comment by aendrew** [comment]
@ergo I don't think so, #926 is still open.

**Comment by aendrew** [comment]
@ergo I've created a new label, `performance`, to make it easier to track performance-related issues. I've been snowed under with work, but once I get a few spare cycles I'm going to try to really get to the bottom of some of these.

**Comment by ribmo** [comment]
Since upgrading to `v0.4.10-rc1` I've started to experience this bug: https://github.com/masayuki0812/c3/issues/1026#issuecomment-77123810

Let me know if there's any other info I can provide to help.

**Comment by SamMorrowDrums** [comment]
:+1:  Great to see such quick movement on this, will try it out before my next deployment :-D

**Comment by masayuki0812** [comment]
I released `v0.4.10-rc2` and this version includes some fixes as you can see here: https://github.com/masayuki0812/c3/releases/tag/0.4.10-rc2

**Comment by ergo** [comment]
Right, I can't migrate because the mem leak bug is still not closed though :(

**Comment by masayuki0812** [comment]
@ergo That bug will not be fixed in 0.4.10. I expect it will be 0.4.11 or more.

**Comment by masayuki0812** [comment]
I released `0.4.10-rc3`, which includes several bug fixes, and I will release `0.4.10` shortly.
https://github.com/masayuki0812/c3/releases/tag/0.4.10-rc3

**Comment by masayuki0812** [comment]
I released `0.4.10-rc4` which includes the fix for initial transition.
https://github.com/masayuki0812/c3/releases/tag/0.4.10-rc4

**Comment by masayuki0812** [comment]
I released `0.4.10-rc5` which includes several bug fixes. This is the final RC version basically and I'll release `0.4.10` soon.
https://github.com/masayuki0812/c3/releases/tag/0.4.10-rc5

**Comment by masayuki0812** [comment]
I released `v0.4.10`.Thanks you for feedbacks and contributions.
https://github.com/masayuki0812/c3/releases/tag/0.4.10
