### ISSUE TITLE
Flowing grouped data

### ISSUE THREAD

**Issue by rhenna** [masayuki0812/c3#1068]
When calling .flow() on grouped data when values are also being pushed off the chart causes an error. Here's an example: http://jsfiddle.net/zavy2cwu/

It also causes some interesting looking results when using a bar chart: http://jsfiddle.net/3jhLau3u/

If flow doesn't push any data off the chart (length: 0), everything seems to be fine: http://jsfiddle.net/aL0sjLkz/

If the data isn't grouped, there aren't any errors, but with bar chart the animation compresses the bars and they expand out again: http://jsfiddle.net/fu41zeg8/

**Comment by mtolek** [comment]
I struggle with the same issue. If the data are not grouped the problem doesn't occur -
http://jsfiddle.net/z2erLqgx/24/
While grouping after calling the .flow() method the chart is not rendered properly -
http://jsfiddle.net/z2erLqgx/23/ 
Console error is:
Uncaught TypeError: Cannot read property 'value' of undefined - c3.js 2736

**Comment by bryyyon** [comment]
Hi.  I encountered this problem and spent some time yesterday trying to find a proper fix on my own.  While looking into this problem I discovered that the targets' values arrays become misaligned even while calling chart.flow() with grouped data of equal lengths.  I think this is due to some sort of problem with older values being added or dropping off (with d3 enter/update/exit pattern).

To me it seems that new values are updated onto some targets but not all when grouping is used.  Then, before all targets are updated, generateGetBarPoints() triggers getShapeOffset() with the misaligned target value arrays.  I'm not familiar with the codebase to make an accurate call here though.

A while into this attempt I discovered issue #1065.  It does indeed fix the problem for us here too.  Very thankful for that from craigsoules!!

I just wanted to let you two know and get a bit more information on this problem out there, in case anyone else encounters it.   Hopefully this can get fixed in the project properly for an upcoming release.

**Comment by masayuki0812** [comment]
I merged https://github.com/masayuki0812/c3/pull/1275 and this will be released in 0.4.11 shortly!

**Comment by say8425** [comment]
Is this issue not solved? In jsfiddle it looks work well. But actually it still has a same error.

**Comment by say8425** [comment]
I think this is not fixed yet.
When x axis is added, then bar is fall down.

http://jsfiddle.net/say8425/h7a8q6r9/8/
