### ISSUE TITLE
slow tooltip on firefox

### ISSUE THREAD

**Issue by Salompas** [masayuki0812/c3#909]
The tooltip in the line chart example posted here: http://c3js.org/samples/tooltip_format.html
is really slow on firefox. Implementing the example (using the code in the snipet) locally won't resolve the issue. (i am using the latest version of c3, i download it today 18/1/2015).

However, the tooltip in the spline example (http://c3js.org/samples/chart_spline.html) runs smoothly on the web. But If I implement it locally I get the same lag issue that occurs with the line chart.

Am I missing something? Has anyone solved this problem? Is there an alternative to the tooltip?

**Comment by Salompas** [comment]
sorry I should've posted this on the forum first, closing this topic

**Comment by aendrew** [comment]
@Salompas This is actually exactly what the issue queue is for. :) Reopening and marking as bug.

**Comment by aendrew** [comment]
(Apologies, just noticed you mentioned the issue only occurred locally, indicating it's probably not a bug and more just an implementation. Google Group is the correct place to post this — thanks!)

**Comment by Salompas** [comment]
The bug actually occurs in the website of the project. If you go to examples->line you'll see that the tool tip is really slow. 

—
Abraços,
Salomé

**Comment by aendrew** [comment]
@Salompas Can't replicate it, works plenty fast in Firefox for me. What version of FF are you using?

**Comment by Salompas** [comment]
Maybe that's the problem. I am using 34.0.5. Some of the examples work smoothly, but others don't.

—
Abraços,
Salomé

**Comment by Salompas** [comment]
Hopefully it's just me.

—
Abraços,
Salomé

**Comment by aendrew** [comment]
@Salompas I'm thinking it's probably just your machine. I've tried the line example with Firefox 33 and 35 and seem fine. Might be worth posting to the Google Group anyway to see whether somebody else has had the issue.

**Comment by Salompas** [comment]
I see. Thanks for testing! 

—
Abraços,
Salomé

**Comment by aendrew** [comment]
Wait, just tried http://c3js.org/samples/tooltip_format.html (not http://c3js.org/samples/simple_multiple.html), and can definitely notice that. Reopening and marking as bug.

**Comment by neilwightman** [comment]
Tested Linux Mint FF 35 64bit:
simple_multiple is very fast
tooltip_format.html is very slow.

**Comment by clarkeash** [comment]
Tested on Mac OS X 10.10.1 (Yosemite) with Firefox 35
Both tooltips work very smooth.

**Comment by aendrew** [comment]
Just adding a note from the Google Group, apparently D3 3.5.3 is causing performance issues, while 3.5.0 is fine.

If you're experiencing this locally, could you try using an older version of D3 and seeing whether it alleviates the problem? It's a bit of a difficult bug to troubleshoot, so any additional reporting you can provide would be super helpful! Thanks! :+1:

**Comment by Salompas** [comment]
I was the one that mentioned that on Google group. I was trying to use c3 with the latest d3 (3.5.3) and I was having those performance issues. I switched to d3 3.5.0 and the tool tip lag stopped. However, the example mentioned previously (hosted on c3 website) is laggy. 

—
Abraços,
Salomé

**Comment by aendrew** [comment]
@Salompas Weird! The website is using D3 v3.4.3!

**Comment by Salompas** [comment]
http://c3js.org/samples/tooltip_format.html is lagging. I noticed that
whenever you move the mouse around the graphic, the scrollbar size changes.

2015-01-20 14:04 GMT-02:00 Ændrew Rininsland <notifications@github.com>:

> @Salompas <https://github.com/Salompas> Weird! The website is using D3
> v3.4.3!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/masayuki0812/c3/issues/909#issuecomment-70678305>.
>



-- 
Guilherme F.P. Salomé
guilhermesalome@gmail.com

**Comment by masayuki0812** [comment]
I just updated d3 in c3js.org to `3.5.0`. Sorry about that..
About scrollbar, it seems to be caused by `y2` axis (I don't see when `y2` axis is not shown), so it's another issue I think.

**Comment by masayuki0812** [comment]
I think this issue was already fixed in the latest verion `0.4.10`, so please let me close at the moment.

**Comment by r0b-** [comment]
Problem still exists for me FF45, D3 2.5.16, C3 0.4.11-rc4 with custom formatter.

Warning in FF dev console seems to be the root cause:
> mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (d3.min.js:3:10379)
