### ISSUE TITLE
Formatting y tick

### ISSUE THREAD

**Issue by skinnybrit51** [masayuki0812/c3#974]
When formatting the y tick the sizing of the chart is not correct.  At the moment the tick label is cut off.  Notice how the dollar sign is cut off. 
![axisyformat](https://cloud.githubusercontent.com/assets/1626261/6023583/8930c5ba-ab93-11e4-95f2-d6a3d88e42d9.png)

**Comment by ttamminen** [comment]
This might be related with https://github.com/masayuki0812/c3/issues/982

We have exactly same issue. Manually setting the padding doesn't work because the font size changes between breakpoints.

**Comment by masayuki0812** [comment]
Sorry for this issue, it's a bug. I think this was fixed by this commit https://github.com/masayuki0812/c3/commit/4140ceb2fca1aae1e3da95d9984639d0980d29df and it's been released as `v0.4.10-rc3`. Can you try this version?
Btw, `0.4.10` is almost ready to release, so I'll let you know when it's released.

**Comment by skinnybrit51** [comment]
This is still an issue for me.  Would overriding the fonts in css cause an issue?

![image](https://cloud.githubusercontent.com/assets/1626261/6646572/b0da19dc-c99c-11e4-97a8-fdf94aaaebd6.png)

**Comment by masayuki0812** [comment]
I don't think so. I tried larger font size, but it seems working.
Btw, I tested with `0.4.10-rc5`, so can you try again with this version? And can you give me a fiddle for your issue?

**Comment by skinnybrit51** [comment]
Tested with rc5 and same issue.  Here's the fiddle.  http://jsfiddle.net/qqqptmdx/2/

**Comment by masayuki0812** [comment]
Thanks for the detail. As I investigated, `.c3 svg` in `c3.css` seems the cause. If I removed this selector, it works as expected. I think `.c3 svg` is not needed because you're specifying `#chart svg`, or please use only `.c3 svg`. Anyway, it seems css matter.

**Comment by skinnybrit51** [comment]
OK.  I can live with making that change in my css.
