### ISSUE TITLE
Stacked Bar Chart Throws Error

### ISSUE THREAD

**Issue by tusharsoni** [masayuki0812/c3#992]
TypeError: Cannot read property 'value' of undefined
    at /bower_components/c3/c3.js:2648:34
    at Array.forEach (native)
    at c3_chart_internal_fn.getShapeOffset (/bower_components/c3/c3.js:2641:21)
    at c3_chart_internal_fn.generateGetBarPoints (/bower_components/c3/c3.js:3139:26)
    at SVGPathElement.c3_chart_internal_fn.generateDrawBar (/bower_components/c3/c3.js:3113:26)
    at /bower_components/d3/d3.min.js:2:31539
    at F (/bower_components/d3/d3.min.js:1:4169)
    at jo (/bower_components/d3/d3.min.js:2:31462)
    at Array.Tl.attr (/bower_components/d3/d3.min.js:5:6117)
    at ChartInternal.c3_chart_internal_fn.addTransitionForBar (/bower_components/c3/c3.js:3086:27)
88c3.js:3156 

------------------------

Uncaught IndexSizeError: Failed to execute 'getItem' on 'SVGPathSegList': The index provided (0) is greater than or equal to the maximum bound (0).

----------------------------

**Comment by goofygrin** [comment]
I've started getting the 

> Uncaught IndexSizeError: Failed to execute 'getItem' on 'SVGPathSegList': The index provided (0) is greater than or equal to the maximum bound (0). 

when I have more than 2 charts on a page.  2 works fine.  the 3rd one I add, the first one doesn't render (although the axes look good) and if you hover you get the above.

**Comment by trsonderm** [comment]
same as goofygrin, I am rendering 4 bar charts on a page. Repeatedly refreshing the page will cause the first bar chart to eventually show. Works fine in firefox.

**Comment by masayuki0812** [comment]
Is this still happening in `v0.4.10-rc4`? It seems I cannot see this issue anymore.

**Comment by trsonderm** [comment]
Confirmed that it is fixed with v0.4.10-rc4. Tested in Chrome v40.0.2214.115 (64-bit).

**Comment by masayuki0812** [comment]
`0.4.10` has been released, so let me close. Thanks!
@trsonderm Thanks for checking!

**Comment by atavakoli** [comment]
Unfortunately, this is still happening on `0.4.10` (Chrome 47.0.2526.106 (64-bit))

**Comment by m-d-s** [comment]
I am still seeing this in Chrome 48.0.2564.97 (64-bit), works fine in firefox.

**Comment by dazhbog** [comment]
Still seeing this in 48.0.2564.103 (64-bit) MAC with 4.10 or 4.11-rc4

**Comment by aendrew** [comment]
@dazhbog I think that's a different issue, relating to SVGPath being removed in recent versions of Chrome. Try the `dev` branch, which includes a polyfill.
